- name: Prepare rootless Podman (UID/GID range, socket)
  shell: bash
  run: |
    set -euo pipefail
    # 1) SubUID/SubGID bereitstellen (großer Bereich)
    USERNAME="$(whoami)"
    if ! grep -q "^${USERNAME}:" /etc/subuid; then
      echo "${USERNAME}:100000:1048576" | sudo tee -a /etc/subuid
    fi
    if ! grep -q "^${USERNAME}:" /etc/subgid; then
      echo "${USERNAME}:100000:1048576" | sudo tee -a /etc/subgid
    fi

    # 2) Tools für Rootless-Overlay & Netz
    sudo zypper -n refresh
    sudo zypper -n install --no-recommends fuse-overlayfs slirp4netns

    # 3) Podman-Konfiguration migrieren
    podman system migrate

    # 4) Docker-API-Socket (rootless) starten
    SOCK="$HOME/podman.sock"
    nohup podman system service --time=0 --log-level=error "unix://$SOCK" >/dev/null 2>&1 &
    for i in {1..30}; do [ -S "$SOCK" ] && break || sleep 1; done
    test -S "$SOCK"
    echo "DOCKER_HOST=unix://$SOCK" >> "$GITHUB_ENV"

    # 5) Optional: Rootless-Storage auf fuse-overlayfs fixieren
    mkdir -p ~/.config/containers
    cat > ~/.config/containers/storage.conf <<'EOF'
    [storage]
    driver = "overlay"
    rootless_storage_path = "$HOME/.local/share/containers/storage"

    [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
    EOF
