- name: Prepare overlay (rootless)
  shell: bash
  run: |
    set -euxo pipefail
    # 1) Pakete
    sudo zypper -n refresh
    sudo zypper -n install --no-recommends fuse-overlayfs slirp4netns

    # 2) SubUID/SubGID (nur wenn noch nicht vorhanden)
    USERNAME="$(whoami)"
    grep -q "^${USERNAME}:" /etc/subuid  || echo "${USERNAME}:100000:1048576" | sudo tee -a /etc/subuid
    grep -q "^${USERNAME}:" /etc/subgid  || echo "${USERNAME}:100000:1048576" | sudo tee -a /etc/subgid

    # 3) storage.conf auf overlay setzen
    mkdir -p ~/.config/containers
    cat > ~/.config/containers/storage.conf <<'EOF'
    [storage]
    driver = "overlay"
    rootless_storage_path = "$HOME/.local/share/containers/storage"
    [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
    EOF
    cat ~/.config/containers/storage.conf

    # 4) Store neu initialisieren
    podman system reset -f || true
    podman system migrate || true

    # 5) Socket starten
    pkill -f "podman system service" || true
    SOCK="$HOME/podman.sock"
    nohup podman system service --time=0 "unix://$SOCK" >/dev/null 2>&1 &
    for i in {1..30}; do [ -S "$SOCK" ] && break || sleep 1; done
    echo "DOCKER_HOST=unix://$SOCK" | tee -a "$GITHUB_ENV"
    echo ">> DOCKER_HOST now: unix://$SOCK"

    # 6) Verifizieren
    echo ">> GraphDriverName:"
    podman info --format '{{ .Store.GraphDriverName }}'  # sollte 'overlay' sein
